### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by giter915** [slavabarkov/railway-infrastructure-segmentation#3]
How do I get the dataset?

**Comment by slavabarkov** [comment]
@giter915 The dataset was originally provided for the participants of the Digital Breakthrough 2022 hackathon. I have the copy on my Google Drive here: https://drive.google.com/drive/folders/1cI1EVuDo2ScppgnuelDKFnFcN0Ox1Lrn

**Comment by giter915** [comment]
> @giter915 The dataset was originally provided for the participants of the Digital Breakthrough 2022 hackathon. I have the copy on my Google Drive here: https://drive.google.com/drive/folders/1cI1EVuDo2ScppgnuelDKFnFcN0Ox1Lrn

thank you very much
