### ISSUE TITLE
How to run ...

### ISSUE THREAD

**Issue by giter915** [slavabarkov/railway-infrastructure-segmentation#4]
Hello,  I would like to ask a question.    src flod    What is the difference between the src directory and the .ipynb file

**Comment by slavabarkov** [comment]
@giter915 All of the data exploration, training and inference is in the Jupyter Notebook .ipynb file. I put some of the functions inside the separate directory so the notebook is less cluttered. These are imported at the beginning in the Jupyter Notebook .ipynb like this: 
```
from src.utils import RunningAverage, iou_coef
from src.data import SegmentationDataset, get_loaders, get_transforms
from src.train import train
from src.inference import get_batch_predictions, upscale_mask, convert_bool_mask_to_submission
from src.visualizations import visualize_augmentations
```

**Comment by slavabarkov** [comment]
You can also check my notebook on Google Colab - https://colab.research.google.com/drive/1ZpusX5_8jv6mvNSe9pwRF0kU9XDCCETN

**Comment by giter915** [comment]
> You can also check my notebook on Google Colab - https://colab.research.google.com/drive/1ZpusX5_8jv6mvNSe9pwRF0kU9XDCCETN
thank you very much!  thanks!
